[toolchain]
channel = "1.92.0"
components = [
  "cargo",
  "clippy",
  "llvm-tools-preview",
  "rust-analyzer",
  "rust-src",
  "rust-std",
  "rustc",
  "rustc-dev",
  "rustfmt"
]
profile = "minimal"
# Only specify host targets - cross will handle Linux/Windows via Docker
#targets = [
#  "aarch64-apple-darwin"
#]
